---
title: "Deconvolution"
author: "Marcelo Hurtado"
date: "2025-06-26"
output: html_document
---

Load libraries
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
```

####################################################################### AUTOLOGOUS

Load data
```{r}
bulk_data = read.delim("Gene_count_matrix_ENS_HGCN_auto.txt", row.names = 1)
m2 <- do.call(rbind, strsplit(rownames(bulk_data), split="_", fixed = TRUE))
bulk_data <- as.matrix(bulk_data)
rownames(bulk_data) = m2[,2]
bulk_data_norm = ADImpute::NormalizeTPM(bulk_data)
```

Deconvolution
```{r}
deconv_autologous = multideconv::compute.deconvolution(bulk_data, normalized = T, credentials.mail = "marcelo.hurtado@inserm.fr", credentials.token = "734212f6ad77fc4eea2bdb502792f294",
                                                       file_name = "autologous", create_signature = F, workers = 6, methods =  c("CBSX", "Epidish", "DWLS"), 
                                                       signatures_exclude = c("BPRNACan","BPRNACan3DProMet", "BPRNACanProMet", "CBSX-HNSCC-scRNAseq", "CBSX-Melanoma-scRNAseq", 
                                                                              "CBSX-NSCLC-PBMCs-scRNAseq", "CCLE-TIL10", "LM22", "TIL10"))
```

BayesPrism deconvolution
```{r}
load("output/scRNAseq_obj.RData")
deconvolution.pseudobulk.bayesprism <- omnideconv::deconvolute_bayesprism(bulk_gene_expression = bulk_data,
                                           single_cell_object = as.matrix(cll_obj@assays$RNA@counts),
                                           cell_type_annotations = cll_obj@meta.data$cell_types,
                                           n_cores=6)

colnames(deconvolution.pseudobulk.bayesprism$theta) = paste0("BayesPrism_", colnames(deconvolution.pseudobulk.bayesprism$theta))
deconv_autologous = cbind(deconv_autologous, deconvolution.pseudobulk.bayesprism$theta)

colnames(deconv_autologous) = stringr::str_replace(colnames(deconv_autologous), "Monocytes/Macrophages", "Monocytes.Macrophages.cells")
```

Choose method-signature
```{r}
#method = "CBSX_CBSX.Cadot_CLL.scRNAseq_"
#method = "CBSX_CBSX.Cadot_CLL_signature.scRNAseq_"
#method = "BayesPrism_"
method = "BayesPrism_sigCLL_"
```

Plot proportions
```{r}
x = deconv_autologous[,grep(method, colnames(deconv_autologous))]
#x = x[,-grep("BayesPrism_sigCLL_", colnames(x))]
x <- x %>% 
  tibble::rownames_to_column("SampleID")

# Parse metadata from SampleID
df_long <- x %>%
  pivot_longer(-SampleID, names_to = "CellType", values_to = "Proportion") %>%
  mutate(
    Timepoint = str_extract(SampleID, "J\\d+"),
    Patient = str_extract(SampleID, "p\\d+"),
    Replicate = str_extract(SampleID, "rep\\d+")
  )

df_avg <- df_long %>%
  group_by(Timepoint, Patient, CellType) %>%
  summarise(MeanProportion = mean(Proportion, na.rm = TRUE), .groups = "drop")

# Plot
p = ggplot(df_avg, aes(x = Timepoint, y = MeanProportion, fill = CellType)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = sprintf("%.5f", MeanProportion)),
              position = position_stack(vjust = 0.5),
              size = 2.5, color = "black") +
    facet_wrap(~ Patient, ncol = 1) +
    coord_flip() +  # Horizontal bars
    labs(title = "Deconvolution per timepoint (Replicates averaged) - Autologous",
         subtitle = method,
         x = "Timepoint", y = "Proportion") +
    scale_fill_brewer(palette = "Set3") +
    theme_minimal(base_size = 12) +
    theme(strip.text = element_text(face = "bold"),
          axis.text.y = element_text(angle = 0, hjust = 1))

pdf(paste0("Deconvolution_autologous_", method, ".pdf"), width = 10)
print(p)
dev.off()
```

####################################################################### MONOCULTURE

Load data
```{r}
bulk_data = read.delim("data/Gene_count_matrix_ENS_HGCN_B.txt", row.names = 1)
m2 <- do.call(rbind, strsplit(rownames(bulk_data), split="_", fixed = TRUE))
bulk_data <- as.matrix(bulk_data)
rownames(bulk_data) = m2[,2]
bulk_data_norm = ADImpute::NormalizeTPM(bulk_data)
```

Deconvolution
```{r}
deconv_mono = multideconv::compute.deconvolution(bulk_data, normalized = T, credentials.mail = "marcelo.hurtado@inserm.fr", credentials.token = "734212f6ad77fc4eea2bdb502792f294",
                                                       file_name = "monoculture", create_signature = F, workers = 6, methods =  c("CBSX", "Epidish", "DWLS"), 
                                                       signatures_exclude = c("BPRNACan","BPRNACan3DProMet", "BPRNACanProMet", "CBSX-HNSCC-scRNAseq", "CBSX-Melanoma-scRNAseq", 
                                                                              "CBSX-NSCLC-PBMCs-scRNAseq", "CCLE-TIL10", "LM22", "TIL10"))
```

BayesPrism deconvolution
```{r}
load("output/scRNAseq_obj_CLL.RData")
deconvolution.pseudobulk.bayesprism <- omnideconv::deconvolute_bayesprism(bulk_gene_expression = bulk_data,
                                           single_cell_object = as.matrix(cll_obj@assays$RNA@counts),
                                           cell_type_annotations = cll_obj@meta.data$cell_types,
                                           n_cores=6)

colnames(deconvolution.pseudobulk.bayesprism$theta) = paste0("BayesPrism_sigCLL_", colnames(deconvolution.pseudobulk.bayesprism$theta))
deconv_mono = cbind(deconv_mono, deconvolution.pseudobulk.bayesprism$theta)

colnames(deconv_mono) = stringr::str_replace(colnames(deconv_mono), "Monocytes/Macrophages", "Monocytes.Macrophages.cells")
```

Choose method-signature
```{r}
#method = "CBSX_CBSX.Cadot_CLL.scRNAseq_"
#method = "CBSX_CBSX.Cadot_CLL_signature.scRNAseq_"
#method = "BayesPrism_"
method = "BayesPrism_sigCLL_"
```

Plot proportions
```{r}
x = deconv_mono[,grep(method, colnames(deconv_mono))]
#x = x[,-grep("BayesPrism_sigCLL_", colnames(x))]
x <- x %>% 
  tibble::rownames_to_column("SampleID")

# Parse metadata from SampleID
df_long <- x %>%
  pivot_longer(-SampleID, names_to = "CellType", values_to = "Proportion") %>%
  mutate(
    Timepoint = str_extract(SampleID, "J\\d+"),
    Patient = str_extract(SampleID, "p\\d+"),
    Replicate = str_extract(SampleID, "rep\\d+")
  )

df_avg <- df_long %>%
  group_by(Timepoint, Patient, CellType) %>%
  summarise(MeanProportion = mean(Proportion, na.rm = TRUE), .groups = "drop")

# Plot
p = ggplot(df_avg, aes(x = Timepoint, y = MeanProportion, fill = CellType)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = sprintf("%.5f", MeanProportion)),
              position = position_stack(vjust = 0.5),
              size = 2.5, color = "black") +
    facet_wrap(~ Patient, ncol = 1) +
    coord_flip() +  # Horizontal bars
    labs(title = "Deconvolution per timepoint (Replicates averaged) - Monoculture",
         subtitle = method,
         x = "Timepoint", y = "Proportion") +
    scale_fill_brewer(palette = "Set3") +
    theme_minimal(base_size = 12) +
    theme(strip.text = element_text(face = "bold"),
          axis.text.y = element_text(angle = 0, hjust = 1))

pdf(paste0("Deconvolution_monoculture_", method, ".pdf"), width = 10)
print(p)
dev.off()
```